# TD1 - Introduction à Pandas

In [3]:
# Importations
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
poids = pd.Series()

In [5]:
# Importing data

In [6]:
# Importer les libraires
# Déclarer les chemins d'accès
# Déclarer les variables globales

In [7]:
url = "https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert"

data = pd.read_csv(url)

In [8]:
# 10 premières valeurs
data.head(10)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756
5,01007,AMBRONAY,4390.996698,132.968268,NaN,3067.245459,6144.186081,122.437003,359.383094,1898.638273,22481.123575,2789.133106
6,01008,AMBUTRIX,489.648726,60.233517,NaN,558.055709,98.388885,2.354558,6.911213,495.393592,3616.168396,356.029873
7,01009,ANDERT-ET-CONDON,676.468367,NaN,NaN,207.181968,149.767083,2.354558,6.911213,141.533662,696.956038,161.266219
8,01010,ANGLEFORT,1070.411510,143.815664,NaN,1286.621447,146.525382,341.410872,175185.892467,448.518801,3199.808360,1206.147643
9,01011,APREMONT,2010.790441,NaN,NaN,249.086914,52.103791,2.354558,6.911213,151.844891,686.153720,188.542701

In [9]:
# 15 dernières lignes
data.tail(15)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
35783,95628,VALMONDOIS,646.421867,9.055189,0.201508,633.754921,158.691749,136.564349,400.850374,2272.901317,589.164544,574.241730
35784,95633,VAUDHERLAND,48.361025,NaN,NaN,47.061403,10.314964,2.354558,6.911213,34.490233,439.279632,199.435133
35785,95637,VAUREAL,203.969473,93.811651,5.412508,2876.820106,129.738126,63.573059,186.602760,13963.143585,4982.982966,7515.388640
35786,95641,VEMARS,1510.886844,146.089307,NaN,2382.550523,19.173651,251.937678,739.499829,2791.215196,17783.179831,2654.384495
35787,95651,VETHEUIL,125.928390,175.096168,10.102258,290.066886,114.522546,16.481904,48.378493,1439.077120,1472.779256,414.411115
35788,95652,VIARMES,252.094735,55.168176,NaN,1278.247866,43.526914,40.027482,117.490627,6546.179324,5705.777606,2521.399729
35789,95656,VIENNE-EN-ARTHIES,324.827105,NaN,NaN,98.346155,57.129030,2.354558,6.911213,158.726900,305.819555,206.727023
35790,95658,VIGNY,1289.190261,NaN,NaN,1616.838995,2297.572718,313.156180,919.191376,1424.373138,8539.961119,516.817557
35791,95660,VILLAINES-SOUS-BOIS,447.132894,18.996282,NaN,207.294216,92.966916,11.772789,34.556067,1023.037832,912.992023,336.409947
35792,95675,VILLERON,1335.123315,4.975886,NaN,1625.523404,104.075339,320.219853,939.925016,617.177184,7740.572805,725.467969
35793,95676,VILLERS-EN-ARTHIES,1628.065094,NaN,NaN,165.045396,65.063617,11.772789,34.556067,176.098160,309.627908,235.439109
35794,95678,VILLIERS-ADAM,698.630772,NaN,NaN,1331.126598,111.480954,2.354558,6.911213,1395.529811,18759.370071,403.404815
35795,95680,VILLIERS-LE-BEL,107.564967,NaN,NaN,8367.174532,225.622903,534.484607,1568.845431,22613.830247,12217.122402,13849.512001
35796,95682,VILLIERS-LE-SEC,1090.890170,NaN,NaN,326.748418,108.969749,2.354558,6.911213,67.235487,4663.232127,85.657725
35797,95690,WY-DIT-JOLI-VILLAGE,1495.103542,NaN,NaN,125.236417,97.728612,4.709115,13.822427,117.450851,504.400972,147.867245

In [10]:
# Echantillon aléatoire

# data.sample(n=10)

# Echantillon de 5% sans remise
a=data.sample( frac=0.05 )

# Tirage avec remise

a= data.head(10).sample(frac=0.05, replace=True)

In [12]:
# Question 4

data4= data.head(6).sample(n=100, weights=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1], replace=True)

# Ou bien

data4 = data.head(6).sample(n=100, weights=[0.5]+ 5*[0.1], replace=True)

In [13]:
# On verra que :
weights=[0.5]+ 5*[0.1]

# Explorons la base

In [14]:
data.axes

[RangeIndex(start=0, stop=35798, step=1),
 Index(['INSEE commune', 'Commune', 'Agriculture', 'Autres transports',
        'Autres transports international', 'CO2 biomasse hors-total', 'Déchets',
        'Energie', 'Industrie hors-énergie', 'Résidentiel', 'Routier',
        'Tertiaire'],
       dtype='str')]

In [15]:
data.columns

Index(['INSEE commune', 'Commune', 'Agriculture', 'Autres transports',
       'Autres transports international', 'CO2 biomasse hors-total', 'Déchets',
       'Energie', 'Industrie hors-énergie', 'Résidentiel', 'Routier',
       'Tertiaire'],
      dtype='str')

In [16]:
data.index

RangeIndex(start=0, stop=35798, step=1)

In [17]:
data.shape

(35798, 12)

In [18]:
data.size

429576

In [19]:
data.shape[0]*data.shape[1] # Equal to size

429576

# Exercices de synthèse

## Exercice 2

In [31]:
emissions = pd.read_csv("https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert")
emissions.head(2)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207

In [32]:
# Création

emissions_copy= emissions.loc[:, ['INSEE commune', 'Commune', 'Autres transports', 'Autres transports international']]
emissions_copy.columns

Index(['INSEE commune', 'Commune', 'Autres transports',
       'Autres transports international'],
      dtype='str')

In [33]:
# Renommons les variables
emissions_copy= emissions_copy.rename({'INSEE commune': 'code_insee','Autres transports' : 'transports', 'Autres transports international' : 'transports_international' }, axis = 1)

emissions_copy.dtypes

code_insee                      str
Commune                         str
transports                  float64
transports_international    float64
dtype: object

Question 3 :

On propose, pour simplifier, de remplacer les valeurs manquantes (NA) par la valeur 0. Utiliser la méthode fillna pour transformer les valeurs manquantes en 0.

In [34]:
emissions_copy = emissions_copy.fillna(0)

Question 4. 
On propose, pour simplifier, de remplacer les valeurs manquantes (NA) par la valeur 0. Utiliser la méthode fillna pour transformer les valeurs manquantes en 0.

In [35]:
emissions_copy['dep'] = emissions_copy['code_insee'].str[:2]

emissions_copy[['dep', 'code_insee']].head()

  dep code_insee
0  01      01001
1  01      01002
2  01      01004
3  01      01005
4  01      01006

In [36]:
emissions_copy['transports_total'] = emissions_copy['transports'] + emissions_copy['transports_international']
emissions_copy['transports_total'].head()

0      0.000000
1      0.000000
2    212.577908
3      0.000000
4      0.000000
Name: transports_total, dtype: float64

Question 5.
Ordonner les données du plus gros pollueur au plus petit puis ordonner les données du plus gros pollueur au plus petit par département (du 01 au 95)

In [42]:
emissions_copy.sort_values(ascending=False, by='transports_total').head()

,code_insee,Commune,transports,transports_international,dep,transports_total
31108,77291,LE MESNIL-AMELOT,133834.090767,3.303394e+06,77,3.437228e+06
31099,77282,MAUREGARD,133699.072712,3.303394e+06,77,3.437093e+06
31111,77294,MITRY-MORY,89815.529858,2.202275e+06,77,2.292090e+06
30438,76351,LE HAVRE,17358.962736,2.109460e+06,76,2.126819e+06
35426,91479,PARAY-VIEILLE-POSTE,513140.971691,7.858782e+05,91,1.299019e+06

In [51]:
emissions_copy.sort_values('transports_total',ascending=False).groupby(by='dep').head()

,code_insee,Commune,transports,transports_international,dep,transports_total
31108,77291,LE MESNIL-AMELOT,133834.090767,3.303394e+06,77,3.437228e+06
31099,77282,MAUREGARD,133699.072712,3.303394e+06,77,3.437093e+06
31111,77294,MITRY-MORY,89815.529858,2.202275e+06,77,2.292090e+06
30438,76351,LE HAVRE,17358.962736,2.109460e+06,76,2.126819e+06
35426,91479,PARAY-VIEILLE-POSTE,513140.971691,7.858782e+05,91,1.299019e+06
...,...,...,...,...,...,...
29515,73008,AIX-LES-BAINS,158.770768,0.000000e+00,73,1.587708e+02
29560,73059,BRISON-SAINT-INNOCENT,155.632021,0.000000e+00,73,1.556320e+02
3133,09282,SAVERDUN,144.229553,0.000000e+00,09,1.442296e+02
2889,09032,AX-LES-THERMES,140.743227,0.000000e+00,09,1.407432e+02
3042,09188,MERCUS-GARRABET,98.416139,0.000000e+00,09,9.841614e+01

,code_insee,Commune,transports,transports_international,dep,transports_total
0,01001,L'ABERGEMENT-CLEMENCIAT,0.000000,0.0,01,0.000000
1,01002,L'ABERGEMENT-DE-VAREY,0.000000,0.0,01,0.000000
2,01004,AMBERIEU-EN-BUGEY,212.577908,0.0,01,212.577908
3,01005,AMBERIEUX-EN-DOMBES,0.000000,0.0,01,0.000000
4,01006,AMBLEON,0.000000,0.0,01,0.000000
...,...,...,...,...,...,...
35613,95002,ABLEIGES,42.448510,0.0,95,42.448510
35614,95008,AINCOURT,0.000000,0.0,95,0.000000
35615,95011,AMBLEVILLE,0.000000,0.0,95,0.000000
35616,95012,AMENUCOURT,0.000000,0.0,95,0.000000
35617,95014,ANDILLY,0.000000,0.0,95,0.000000

Question 6. Ne conserver que les communes appartenant aux départements 13 ou 31. Ordonner ces communes du plus gros pollueur au plus petit.

In [65]:
emissions_q6 = emissions_copy.where((emissions_copy['dep'] == '13') | (emissions_copy['dep'] == '31'))
emissions_q6.head(6)

,code_insee,Commune,transports,transports_international,dep,transports_total
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
emissions_copy['dep'].unique()

<ArrowStringArray>
['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13',
 '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27',
 '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38',
 '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51',
 '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64',
 '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77',
 '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90',
 '91', '92', '93', '94', '95']
Length: 96, dtype: str